#This workflow is for tracking issues and displaying them to discord when updated

name: amplyst-issues

on:
  issues:
    types: [edited]

jobs:
  trigger-discord:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Trigger Discord
      uses: sarisia/actions-status-discord@v1.8.6
      if: always()
      with:
        webhook: ${{ secrets.DISCORD_ISSUE_TRACKER }}
        nodetail: true
        title: "[${{github.event.repository.name}}] Git Issue was Edited:"
        description: |
          Title: [${{github.event.issue.title}}]
          Description: ${{github.event.issues.body}}