# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: amplyst-ci

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  flask-lint:
    runs-on: ubuntu-latest

    steps:
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

  flask-build:
    needs: flask-lint
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      working-directory: api
    - name: Run Flask
      run: |
        nohup python3 app.py &
        sleep 5
      working-directory: api
    - name: Actions Status Discord
      uses: sarisia/actions-status-discord@v1.8.6
      if: always()
      with:
        title: "amplyst-ci - flask-build"
        webhook: ${{secrets.DISCORD_WEBHOOK }}


  react-build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Node ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Dependencies
      run: |
        npm ci
        npm run build --if-present
        npm install -g eslint
      working-directory: client
    - name: Lint with eslint
      run: |
        ls -a
        eslint --init 
        eslint ./src
      working-directory: client
    - name: Run React
      run: |
        npm init -y
        npm test
    - name: Actions Status Discord
      uses: sarisia/actions-status-discord@v1.8.6
      if: always()
      with:
        title: "amplyst-ci - react-build"
        webhook: ${{secrets.DISCORD_WEBHOOK }}

