inputs:
  name:
    os: ubuntu-latest
    default: ubuntu-latest
runs:
  using: "composite"
  steps:
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      working-directory: api
    - name: Run Flask
      run: |
        python3 app.py
